---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by heyqule.
--- DateTime: 7/18/2023 2:09 AM
---

local AnimationDB = require('__erm_libs__/prototypes/animation_db')

--- Naming convention EntityType_Name. EntityType follows the graphics folder structure.
--- e.g [unit][zergling], [building][hive], [projectiles][spore], etc
---
--- death and projectile are handled differently because they are mostly single layer animation.
AnimationDB.data = {
    buildings = {
        overmind = require('__erm_zerg_hd_assets__/db/buildings/boss_overmind'),
        chamber = require('__erm_zerg_hd_assets__/db/buildings/chamber'),
        defiler_mound = require('__erm_zerg_hd_assets__/db/buildings/defiler_mound'),
        greater_spire = require('__erm_zerg_hd_assets__/db/buildings/greater_spire'),
        hatchery = require('__erm_zerg_hd_assets__/db/buildings/hatchery'),
        hive = require('__erm_zerg_hd_assets__/db/buildings/hive'),
        hydraden = require('__erm_zerg_hd_assets__/db/buildings/hydraden'),
        infested_cmd = require('__erm_zerg_hd_assets__/db/buildings/infested_cmd'),
        infested_cmd_infestor = require('__erm_zerg_hd_assets__/db/buildings/infested_cmd_infestor'),
        lair = require('__erm_zerg_hd_assets__/db/buildings/lair'),
        nyduspit = require('__erm_zerg_hd_assets__/db/buildings/nyduspit'),
        queen_nest = require('__erm_zerg_hd_assets__/db/buildings/queen_nest'),
        spawning_pool = require('__erm_zerg_hd_assets__/db/buildings/spawning_pool'),
        spire = require('__erm_zerg_hd_assets__/db/buildings/spire'),
        spore_colony = require('__erm_zerg_hd_assets__/db/buildings/spore_colony'),
        sunken_colony = require('__erm_zerg_hd_assets__/db/buildings/sunken_colony'),
        ultralisk_cavern = require('__erm_zerg_hd_assets__/db/buildings/ultralisk_cavern'),
    },
    death = require('__erm_zerg_hd_assets__/db/death'),
    projectiles = require('__erm_zerg_hd_assets__/db/projectiles'),
    units = {
        broodling = require('__erm_zerg_hd_assets__/db/units/broodling'),
        defiler = require('__erm_zerg_hd_assets__/db/units/defiler'),
        devourer = require('__erm_zerg_hd_assets__/db/units/devourer'),
        drone = require('__erm_zerg_hd_assets__/db/units/drone'),
        guardian = require('__erm_zerg_hd_assets__/db/units/guardian'),
        hydralisk = require('__erm_zerg_hd_assets__/db/units/hydralisk'),
        infested = require('__erm_zerg_hd_assets__/db/units/infested'),
        lurker = require('__erm_zerg_hd_assets__/db/units/lurker'),
        mutalisk = require('__erm_zerg_hd_assets__/db/units/mutalisk'),
        overlord = require('__erm_zerg_hd_assets__/db/units/overlord'),
        queen = require('__erm_zerg_hd_assets__/db/units/queen'),
        scourge = require('__erm_zerg_hd_assets__/db/units/scourge'),
        ultralisk = require('__erm_zerg_hd_assets__/db/units/ultralisk'),
        zergling = require('__erm_zerg_hd_assets__/db/units/zergling'),
    },
    default_team_color = {r=96, g=48, b=0, a=166}
    --default_team_color = {r=128, g=64, b=0, a=0}
}

return AnimationDB