---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by SHlNZ0U.
--- DateTime: 17/07/2023 2:48 PM
---

local final_render_layer = 'decals'
if mods['alien-biomes'] then
    final_render_layer = "lower-radius-visualization"
end

data:extend({
    --- Creep
    {
        name = "creep-decal",
        type = "optimized-decorative",
        order = "b[decorative]-b[creep-decal]",
        collision_box = { { -6, -4 }, { 6, 4 } },
        collision_mask = { "water-tile", "colliding-with-tiles-only" },
        render_layer = final_render_layer,
        tile_layer = 58,
        pictures = {
            {
                filename = "__erm_zerg_hd_assets__/graphics/decorative/creep-decal/creep-decal-00.png",
                width = 1118,
                height = 799,
                draw_as_glow = true,
                shift = util.by_pixel(0, 0),
                scale = 0.75
            },
            {
                filename = "__erm_zerg_hd_assets__/graphics/decorative/creep-decal/creep-decal-01.png",
                width = 998,
                height = 722,
                draw_as_glow = true,
                shift = util.by_pixel(-4, 1),
                scale = 0.75
            },
            {
                filename = "__erm_zerg_hd_assets__/graphics/decorative/creep-decal/creep-decal-02.png",
                width = 1014,
                height = 718,
                draw_as_glow = true,
                shift = util.by_pixel(0, 0),
                scale = 0.75
            },
            {
                filename = "__erm_zerg_hd_assets__/graphics/decorative/creep-decal/creep-decal-03.png",
                width = 1010,
                height = 718,
                draw_as_glow = true,
                shift = util.by_pixel(1, 0),
                scale = 0.75
            },
            {
                filename = "__erm_zerg_hd_assets__/graphics/decorative/creep-decal/creep-decal-04.png",
                width = 862,
                height = 722,
                draw_as_glow = true,
                shift = util.by_pixel(4, 0),
                scale = 0.75
            },
            {
                filename = "__erm_zerg_hd_assets__/graphics/decorative/creep-decal/creep-decal-05.png",
                width = 920,
                height = 578,
                draw_as_glow = true,
                shift = util.by_pixel(14, -1),
                scale = 0.75
            },
            {
                filename = "__erm_zerg_hd_assets__/graphics/decorative/creep-decal/creep-decal-06.png",
                width = 968,
                height = 708,
                draw_as_glow = true,
                shift = util.by_pixel(3, -2),
                scale = 0.75
            },
            {
                filename = "__erm_zerg_hd_assets__/graphics/decorative/creep-decal/creep-decal-07.png",
                width = 1016,
                height = 722,
                draw_as_glow = true,
                shift = util.by_pixel(0, -1),
                scale = 0.75
            }
        }
    },
    {
        name = "creep-decal-transparent",
        type = "optimized-decorative",
        order = "b[decorative]-b[creep-decal]",
        collision_box = { { -6, -4 }, { 6, 4 } },
        collision_mask = { "water-tile", "colliding-with-tiles-only" },
        render_layer = final_render_layer,
        tile_layer = 57,
        pictures = {
            {
                filename = "__erm_zerg_hd_assets__/graphics/decorative/creep-decal/creep-decal-t-00.png",
                width = 1118,
                height = 792,
                draw_as_glow = true,
                shift = util.by_pixel(0, -2),
                scale = 0.75
            },
            {
                filename = "__erm_zerg_hd_assets__/graphics/decorative/creep-decal/creep-decal-t-01.png",
                width = 936,
                height = 570,
                draw_as_glow = true,
                shift = util.by_pixel(-3, 23),
                scale = 0.75
            },
            {
                filename = "__erm_zerg_hd_assets__/graphics/decorative/creep-decal/creep-decal-t-02.png",
                width = 848,
                height = 540,
                draw_as_glow = true,
                shift = util.by_pixel(-4, 23),
                scale = 0.75
            },
            {
                filename = "__erm_zerg_hd_assets__/graphics/decorative/creep-decal/creep-decal-t-03.png",
                width = 968,
                height = 690,
                draw_as_glow = true,
                shift = util.by_pixel(4, -7),
                scale = 0.75
            },
            {
                filename = "__erm_zerg_hd_assets__/graphics/decorative/creep-decal/creep-decal-t-04.png",
                width = 800,
                height = 720,
                draw_as_glow = true,
                shift = util.by_pixel(7, -2),
                scale = 0.75
            },
            {
                filename = "__erm_zerg_hd_assets__/graphics/decorative/creep-decal/creep-decal-t-05.png",
                width = 888,
                height = 521,
                draw_as_glow = true,
                shift = util.by_pixel(17, 3),
                scale = 0.75
            },
            {
                filename = "__erm_zerg_hd_assets__/graphics/decorative/creep-decal/creep-decal-t-06.png",
                width = 916,
                height = 602,
                draw_as_glow = true,
                shift = util.by_pixel(6, 9),
                scale = 0.75
            },
            {
                filename = "__erm_zerg_hd_assets__/graphics/decorative/creep-decal/creep-decal-t-07.png",
                width = 1004,
                height = 710,
                draw_as_glow = true,
                shift = util.by_pixel(3, -3),
                scale = 0.75
            }
        }
    }
})