---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by heyqule.
--- DateTime: 7/18/2023 9:07 PM
---


return {
    small_rubble = {
        run = {
            main = {
                filename = "__erm_zerg_hd_assets__/graphics/entity/buildings/death/zerg_small_rubble.png",
                variation_count = 4,
                width = 386,
                height = 377,
                frame_count = 1,
                direction_count = 1,
                scale = 0.5
            }
        }
    },
    large_rubble = {
        run = {
            main =             {
                filename = "__erm_zerg_hd_assets__/graphics/entity/buildings/death/zerg_large_rubble.png",
                width = 509,
                height = 505,
                variation_count = 4,
                frame_count = 1,
                direction_count = 1,
                scale = 0.5
            }
        }
    },
    large_building = {
        explosion = {
            main = {
                filename = "__erm_zerg_hd_assets__/graphics/entity/buildings/death/zerg_building_blood_large.png",
                width = 550,
                height = 656,
                frame_count = 8,
                animation_speed = 0.4,
                direction_count = 1,
                scale = 0.7
            }
        }
    },
    small_building = {
        explosion = {
            main = {
                filename = "__erm_zerg_hd_assets__/graphics/entity/buildings/death/zerg_building_blood_small.png",
                width = 344,
                height = 342,
                frame_count = 8,
                animation_speed = 0.4,
                direction_count = 1,
                scale = 0.7
            }
        }
    },
    terran_cmd = {
        explosion = {
            main = {
                filename = "__erm_zerg_hd_assets__/graphics/entity/buildings/death/terran_building_explosion_large.png",
                width = 819,
                height = 661,
                frame_count = 10,
                animation_speed = 0.4,
                direction_count = 1,
                scale = 0.7,
                draw_as_glow = true,
            }
        }
    }
}