---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by heyqule.
--- DateTime: 7/18/2023 11:18 AM
---

return {
    hydralisk = {
        attack_attachment = {
            main = {
                filename = "__erm_zerg_hd_assets__/graphics/entity/projectiles/hydra_split.png",
                width = 257,
                height = 198,
                frame_count = 6,
                axially_symmetrical = false,
                direction_count = 16,
                scale = 0.4,
                animation_speed = 0.4
            }
        },
        projectile = {
            main =  {
                filename = "__erm_zerg_hd_assets__/graphics/entity/projectiles/hydra_pr.png",
                frame_count = 1,
                width = 78,
                height = 148,
                animation_speed = 0.4,
                scale = 0.4
            }
        },
        explosion = {
            main = {
                filename = "__erm_zerg_hd_assets__/graphics/entity/projectiles/hydra_acid.png",
                width = 170,
                height = 171,
                line_length = 8,
                frame_count = 8,
                animation_speed = 0.4,
                scale = 0.4
            }
        }
    },
    mutalisk = {
        projectile = {
            main =  {
                filename = "__erm_zerg_hd_assets__/graphics/entity/projectiles/spores_1.png",
                frame_count = 10,
                width = 168,
                height = 146,
                scale = 0.5,
                animation_speed = 0.4,
                run_mode = 'forward-then-backward'
            }
        },
        explosion = {
            main =     {
                filename = "__erm_zerg_hd_assets__/graphics/entity/projectiles/mutalisk_explosion.png",
                width = 158,
                height = 263,
                frame_count = 10,
                animation_speed = 0.4,
                scale = 1
            }
        }
    },
    guardian = {
        projectile = {
            main =   {
                filename = "__erm_zerg_hd_assets__/graphics/entity/projectiles/spores_2.png",
                width = 107,
                height = 108,
                frame_count = 4,
                animation_speed = 0.4,
                scale = 0.5
            }
        }
    },
    parasite = {
        projectile = {
            main = {
                filename = "__erm_zerg_hd_assets__/graphics/entity/units/parasite/parasite-run.png",
                width = 89,
                height = 81,
                frame_count = 1,
                axially_symmetrical = false,
                direction_count = 16,
                scale = 0.5,
                animation_speed = 0.4
            },
            shadow = {
                shift = { 4, 0 }
            },
            team = {
                filename = "__erm_zerg_hd_assets__/graphics/entity/units/parasite/parasite-run_teamcolour.png",
                width = 89,
                height = 81,
                frame_count = 1,
                axially_symmetrical = false,
                direction_count = 16,
                scale = 0.5,
                animation_speed = 0.4
            }
        }
    },
    lurker = {
        explosion = {
            main =     {
                filename = "__erm_zerg_hd_assets__/graphics/entity/projectiles/lurker_spike.png",
                width = 674,
                height = 556,
                frame_count = 7,
                animation_speed = 0.4,
                scale = 0.75,
                run_mode = "forward-then-backward",
            }
        }
    },
    colony = {
        explosion = {
            main =   {
                filename = "__erm_zerg_hd_assets__/graphics/entity/projectiles/colony_spike.png",
                width = 736,
                height = 537,
                frame_count = 6,
                animation_speed = 0.4,
                scale = 0.5,
                run_mode = "forward-then-backward",
            },
            shadow = {
                shift = { 0.15, 0.1 }
            }
        }
    },
    blood_cloud = {
        explosion = {
            main =     {
                filename = "__erm_zerg_hd_assets__/graphics/entity/projectiles/defiler_blood.png",
                width = 682,
                height = 594,
                frame_count = 12,
                animation_speed = 0.4,
                scale = 0.5
            }
        }
    },
    dark_swam_80 = {
        explosion = {
            main =     {
                filename = "__erm_zerg_hd_assets__/graphics/entity/projectiles/darkswarm-80.png",
                width = 256,
                height = 256,
                frame_count = 35,
                frame_sequence = {1,2,3,4,5,6,7,8,9,10,9,8,7,6,7,8,9,10,9,8,7,6,7,8,9,10,9,8,7,6,5,4,3,2,1},
                animation_speed = 0.4,
                scale = 2
            }
        }
    },
    dark_swam = {
        explosion = {
            main =     {
                filename = "__erm_zerg_hd_assets__/graphics/entity/projectiles/darkswarm.png",
                width = 1060,
                height = 832,
                line_length = 5,
                frame_count = 60,
                frame_sequence = {1,2,3,4,5,6,7,8,9,10,9,8,7,6,7,8,9,10,9,8,7,6,7,8,9,10,9,8,7,6,7,8,9,10,9,8,7,6,7,8,9,10,9,8,7,6,7,8,9,10,9,8,7,6,5,4,3,2,1},
                animation_speed = 0.4,
                scale = 0.5
            }
        }
    },
    acid_cloud = {
        explosion = {
            main =     {
                filename = "__erm_zerg_hd_assets__/graphics/entity/projectiles/snare.png",
                width = 596,
                height = 743,
                frame_count = 13,
                animation_speed = 0.4,
                scale = 0.5
            }
        }
    },
    devourer_cloud = {
        explosion = {
            main = {
                filename = "__erm_zerg_hd_assets__/graphics/entity/projectiles/devourer_puke_hit.png",
                width = 462,
                height = 475,
                frame_count = 10,
                animation_speed = 0.4,
                scale = 0.375
            }
        }
    },
    scourge_explosion = {
        explosion = {
            main = {
                filename = "__erm_zerg_hd_assets__/graphics/entity/projectiles/scourge_explosion.png",
                width = 200,
                height = 202,
                frame_count = 9,
                animation_speed = 0.4,
                scale = 0.4
            },
            team = {
                filename = "__erm_zerg_hd_assets__/graphics/entity/projectiles/scourge_explosion_teamcolour.png",
                width = 200,
                height = 202,
                frame_count = 9,
                animation_speed = 0.4,
                scale = 0.4
            }
        }
    }
}