---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by heyqule.
--- DateTime: 7/18/2023 8:15 AM
---

return {
    run = {
        main =             {
            filename = "__erm_zerg_hd_assets__/graphics/entity/units/broodling/broodling-run.png",
            width = 240,
            height = 220,
            frame_count = 6,
            axially_symmetrical = false,
            direction_count = 16,
            scale = 0.3,
            animation_speed = 0.4,
        },
        shadow = {
            shift = { 0.2, 0 }
        },
        team =             {
            filename = "__erm_zerg_hd_assets__/graphics/entity/units/broodling/broodling-run_teamcolour.png",
            width = 240,
            height = 220,
            frame_count = 6,
            axially_symmetrical = false,
            direction_count = 16,
            scale = 0.3,
            animation_speed = 0.4,
        }
    },
    attack = {
        main =             {
            filename = "__erm_zerg_hd_assets__/graphics/entity/units/broodling/broodling-attack.png",
            width = 240,
            height = 220,
            frame_count = 6,
            axially_symmetrical = false,
            direction_count = 16,
            scale = 0.3,
            animation_speed = 0.4,
        },
        shadow = {
            shift = { 0.2, 0 }
        }
    },
    corpse = {
        main = {
            filename = "__erm_zerg_hd_assets__/graphics/entity/units/broodling/broodling-death.png",
            width = 242,
            height = 222,
            frame_count = 2,
            direction_count = 1,
            axially_symmetrical = false,
            scale = 0.3,
            animation_speed = 0.4
        }
    }
}