---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by heyqule.
--- DateTime: 7/18/2023 8:15 AM
---

return {
    run = {
        main =            {
            filename = "__erm_zerg_hd_assets__/graphics/entity/units/devourer/devourer-run.png",
            width = 376,
            height = 401,
            frame_count = 5,
            axially_symmetrical = false,
            direction_count = 16,
            scale =  0.375,
            animation_speed = 0.4,
            run_mode = 'forward-then-backward'
        },
        shadow = {
            shift = { 4, 0 }
        },
        team =            {
            filename = "__erm_zerg_hd_assets__/graphics/entity/units/devourer/devourer-run_teamcolour.png",
            width = 376,
            height = 401,
            frame_count = 5,
            axially_symmetrical = false,
            direction_count = 16,
            scale =  0.375,
            animation_speed = 0.4,
            run_mode = 'forward-then-backward'
        },
    },
    attack = {
        main =             {
            filename = "__erm_zerg_hd_assets__/graphics/entity/units/devourer/devourer-attack.png",
            width = 376,
            height = 401,
            frame_count = 5,
            axially_symmetrical = false,
            direction_count = 16,
            scale = 0.375,
            animation_speed = 0.2,
            run_mode = 'forward-then-backward'
        },
        shadow = {
            shift = { 4, 0 }
        },
        team =            {
            filename = "__erm_zerg_hd_assets__/graphics/entity/units/devourer/devourer-attack_teamcolour.png",
            width = 376,
            height = 401,
            frame_count = 5,
            axially_symmetrical = false,
            direction_count = 16,
            scale =  0.375,
            animation_speed = 0.4,
            run_mode = 'forward-then-backward'
        },
    },
    corpse = {
        main = {
            filename = "__erm_zerg_hd_assets__/graphics/entity/units/devourer/devourer-death.png",
            width = 552,
            height = 658,
            frame_count = 8,
            direction_count = 1,
            axially_symmetrical = false,
            scale = 0.375,
            animation_speed = 0.4
        }
    }
}