---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by heyqule.
--- DateTime: 7/18/2023 8:15 AM
---

return {
    run = {
        main = {
            filenames =
            {
                "__erm_zerg_hd_assets__/graphics/entity/units/drone/drone-run-0.png",
                "__erm_zerg_hd_assets__/graphics/entity/units/drone/drone-run-1.png",
            },
            width = 525,
            height = 536,
            frame_count = 5,
            axially_symmetrical = false,
            direction_count = 16,
            scale = 0.4,
            animation_speed = 0.4,
            slice = 5,
            lines_per_file = 8,
            line_length = 5,
        },
        shadow = {
            shift = { 0.2, 0 }
        },
        team = {
            filenames =
            {
                "__erm_zerg_hd_assets__/graphics/entity/units/drone/drone-run_teamcolour-0.png",
                "__erm_zerg_hd_assets__/graphics/entity/units/drone/drone-run_teamcolour-1.png",
            },
            width = 525,
            height = 536,
            frame_count = 5,
            axially_symmetrical = false,
            direction_count = 16,
            scale = 0.4,
            animation_speed = 0.4,
            slice = 5,
            lines_per_file = 8,
            line_length = 5,
        }
    },
    attack = {
        main =             {
            filename = "__erm_zerg_hd_assets__/graphics/entity/units/drone/drone-construction.png",
            width = 706,
            height = 756,
            frame_count = 7,
            axially_symmetrical = false,
            direction_count = 1,
            scale = 0.4,
            animation_speed = 0.2,
            repeat_count = 12,
        },
        shadow = {
            shift = { 0.2, 0 }
        }
    },
    corpse = {
        main = {
            filename = "__erm_zerg_hd_assets__/graphics/entity/units/drone/drone-death.png",
            width = 525,
            height = 536,
            frame_count = 7,
            direction_count = 1,
            axially_symmetrical = false,
            scale = 0.4,
            animation_speed = 0.4
        }
    }
}