---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by heyqule.
--- DateTime: 7/18/2023 8:15 AM
---

return {
    run = {
        main =                  {
            filenames = {
                "__erm_zerg_hd_assets__/graphics/entity/units/hydralisk/hydralisk-run-0.png",
                "__erm_zerg_hd_assets__/graphics/entity/units/hydralisk/hydralisk-run-1.png",
            },
            frame_count = 6,
            slice = 6,
            lines_per_file = 8,
            line_length = 6,
            width = 549,
            height = 528,
            axially_symmetrical = false,
            direction_count = 16,
            scale = 0.4,
            animation_speed = 0.4,
        },
        shadow = {
            shift = { 0.2, 0 }
        },
        team =                  {
            filenames = {
                "__erm_zerg_hd_assets__/graphics/entity/units/hydralisk/hydralisk-run_teamcolour-0.png",
                "__erm_zerg_hd_assets__/graphics/entity/units/hydralisk/hydralisk-run_teamcolour-1.png",
            },
            frame_count = 6,
            slice = 6,
            lines_per_file = 8,
            line_length = 6,
            width = 549,
            height = 528,
            axially_symmetrical = false,
            direction_count = 16,
            scale = 0.4,
            animation_speed = 0.4,
        },
    },
    attack = {
        main = {
            filenames = {
                "__erm_zerg_hd_assets__/graphics/entity/units/hydralisk/hydralisk-attack-0.png",
                "__erm_zerg_hd_assets__/graphics/entity/units/hydralisk/hydralisk-attack-1.png",
            },
            frame_count = 6,
            slice = 6,
            lines_per_file = 8,
            line_length = 6,
            width = 549,
            height = 528,
            axially_symmetrical = false,
            direction_count = 16,
            scale = 0.4,
            animation_speed = 0.4
        },
        shadow = {
            shift = { 0.2, 0 }
        },
        team = {
            filenames = {
                "__erm_zerg_hd_assets__/graphics/entity/units/hydralisk/hydralisk-attack_teamcolour-0.png",
                "__erm_zerg_hd_assets__/graphics/entity/units/hydralisk/hydralisk-attack_teamcolour-1.png",
            },
            frame_count = 6,
            slice = 6,
            lines_per_file = 8,
            line_length = 6,
            width = 549,
            height = 528,
            axially_symmetrical = false,
            direction_count = 16,
            scale = 0.4,
            animation_speed = 0.4
        }
    },
    corpse = {
        main = {
            filename = "__erm_zerg_hd_assets__/graphics/entity/units/hydralisk/hydralisk-death.png",
            width = 549,
            height = 528,
            frame_count = 8,
            direction_count = 1,
            axially_symmetrical = false,
            scale = 0.4,
            animation_speed = 0.4
        }
    }
}