---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by heyqule.
--- DateTime: 7/18/2023 8:15 AM
---

return {
    run = {
        main =             {
            filenames = {
                "__erm_zerg_hd_assets__/graphics/entity/units/infested/infested-run-0.png",
                "__erm_zerg_hd_assets__/graphics/entity/units/infested/infested-run-1.png",
            },
            width = 298,
            height = 271,
            frame_count = 8,
            slice = 8,
            lines_per_file = 8,
            line_length = 8,
            axially_symmetrical = false,
            direction_count = 16,
            scale = 0.4,
            animation_speed = 0.4,
        },
        shadow = {
            shift = { 0.2, 0 }
        },
        team = {
            filenames = {
                "__erm_zerg_hd_assets__/graphics/entity/units/infested/infested-run_teamcolour-0.png",
                "__erm_zerg_hd_assets__/graphics/entity/units/infested/infested-run_teamcolour-1.png",
            },
            width = 298,
            height = 271,
            frame_count = 8,
            slice = 8,
            lines_per_file = 8,
            line_length = 8,
            axially_symmetrical = false,
            direction_count = 16,
            scale = 0.4,
            animation_speed = 0.4,
        }
    },
    corpse = {
        main = {
            filename = "__erm_zerg_hd_assets__/graphics/entity/units/infested/infested-death.png",
            width = 300,
            height = 273,
            frame_count = 8,
            direction_count = 1,
            axially_symmetrical = false,
            scale = 0.4,
            animation_speed = 0.4
        }
    }
}