---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by heyqule.
--- DateTime: 7/18/2023 8:15 AM
---

return {
    run = {
        main =             {
            filename = "__erm_zerg_hd_assets__/graphics/entity/units/lurker/lurker-run.png",
            width = 512,
            height = 485,
            frame_count = 7,
            axially_symmetrical = false,
            direction_count = 16,
            scale = 0.4,
            animation_speed = 0.4,
        },
        shadow = {
            shift = { 0.2, 0 }
        },
        team =             {
            filename = "__erm_zerg_hd_assets__/graphics/entity/units/lurker/lurker-run_teamcolour.png",
            width = 512,
            height = 485,
            frame_count = 7,
            axially_symmetrical = false,
            direction_count = 16,
            scale = 0.4,
            animation_speed = 0.4,
        },
    },
    attack = {
        main =             {
            filename = "__erm_zerg_hd_assets__/graphics/entity/units/lurker/lurker-attack.png",
            width = 512,
            height = 485,
            frame_count = 23,
            frame_sequence = {1,2,3,4,5,6,7,7,7,7,7,7,7,7,7,7,7,7,7,8,9,10,11},
            direction_count = 1,
            scale = 0.4,
            animation_speed = 0.4
        },
        shadow = {
            shift = { 0.2, 0 }
        },
        team =             {
            filename = "__erm_zerg_hd_assets__/graphics/entity/units/lurker/lurker-attack_teamcolour.png",
            width = 512,
            height = 485,
            frame_count = 23,
            frame_sequence = {1,2,3,4,5,6,7,7,7,7,7,7,7,7,7,7,7,7,7,8,9,10,11},
            direction_count = 1,
            scale = 0.4,
            animation_speed = 0.4
        },
    },
    corpse = {
        main = {
            filename = "__erm_zerg_hd_assets__/graphics/entity/units/lurker/lurker-death.png",
            width = 514,
            height = 487,
            frame_count = 7,
            direction_count = 1,
            axially_symmetrical = false,
            scale = 0.4,
            animation_speed = 0.4
        }
    }
}