---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by heyqule.
--- DateTime: 7/18/2023 8:15 AM
---

return {
    run = {
        main = {
            filenames = {
                "__erm_zerg_hd_assets__/graphics/entity/units/mutalisk/mutalisk-run-0.png",
                "__erm_zerg_hd_assets__/graphics/entity/units/mutalisk/mutalisk-run-1.png"
            },
            width = 520,
            height = 512,
            frame_count = 5,
            slice = 5,
            lines_per_file = 8,
            line_length = 5,
            axially_symmetrical = false,
            direction_count = 16,
            scale = 0.4,
            animation_speed = 0.4
        },
        shadow = {
            shift = { 4, 0 }
        },
        team = {
            filenames = {
                "__erm_zerg_hd_assets__/graphics/entity/units/mutalisk/mutalisk-run_teamcolour-0.png",
                "__erm_zerg_hd_assets__/graphics/entity/units/mutalisk/mutalisk-run_teamcolour-1.png"
            },
            width = 520,
            height = 512,
            frame_count = 5,
            slice = 5,
            lines_per_file = 8,
            line_length = 5,
            axially_symmetrical = false,
            direction_count = 16,
            scale = 0.4,
            animation_speed = 0.4
        },
    },
    corpse = {
        main = {
            filename = "__erm_zerg_hd_assets__/graphics/entity/units/mutalisk/mutalisk-death.png",
            width = 346,
            height = 344,
            frame_count = 7,
            direction_count = 1,
            axially_symmetrical = false,
            scale = 0.4,
            animation_speed = 0.4
        }
    }
}