---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by heyqule.
--- DateTime: 7/18/2023 8:15 AM
---

return {
    run = {
        main = {
            filename = "__erm_zerg_hd_assets__/graphics/entity/units/queen/queen-run.png",
            width = 538,
            height = 512,
            frame_count = 6,
            axially_symmetrical = false,
            direction_count = 16,
            scale = 0.375,
            animation_speed = 0.4,
        },
        shadow = {
            shift = { 4, 0 }
        },
        team = {
            filename = "__erm_zerg_hd_assets__/graphics/entity/units/queen/queen-run_teamcolour.png",
            width = 538,
            height = 512,
            frame_count = 6,
            axially_symmetrical = false,
            direction_count = 16,
            scale = 0.375,
            animation_speed = 0.4,
        },
    },
    attack = {
        main =             {
            filename = "__erm_zerg_hd_assets__/graphics/entity/units/queen/queen-attack.png",
            width = 538,
            height = 512,
            frame_count = 5,
            axially_symmetrical = false,
            direction_count = 16,
            scale = 0.375,
            animation_speed = 0.4
        },
        shadow = {
            shift = { 4, 0 }
        },
        team =             {
            filename = "__erm_zerg_hd_assets__/graphics/entity/units/queen/queen-attack_teamcolour.png",
            width = 538,
            height = 512,
            frame_count = 5,
            axially_symmetrical = false,
            direction_count = 16,
            scale = 0.375,
            animation_speed = 0.4
        },
    },
    corpse = {
        main = {
            filename = "__erm_zerg_hd_assets__/graphics/entity/units/queen/queen-death.png",
            width = 552,
            height = 650,
            frame_count = 8,
            direction_count = 1,
            axially_symmetrical = false,
            scale =  0.375,
            animation_speed = 0.4
        }
    }
}