---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by heyqule.
--- DateTime: 7/18/2023 8:15 AM
---

return {
    run = {
        main = {
            filename = "__erm_zerg_hd_assets__/graphics/entity/units/scourge/scourge-run.png",
            width = 196,
            height = 182,
            frame_count = 5,
            axially_symmetrical = false,
            direction_count = 16,
            scale = 0.4,
            animation_speed = 0.4
        },
        shadow = {
            shift = { 4, 0 }
        },
        team = {
            filename = "__erm_zerg_hd_assets__/graphics/entity/units/scourge/scourge-run_teamcolour.png",
            width = 196,
            height = 182,
            frame_count = 5,
            axially_symmetrical = false,
            direction_count = 16,
            scale = 0.4,
            animation_speed = 0.4
        },
    },
    corpse = {
        main = {
            filename = "__erm_zerg_hd_assets__/graphics/entity/units/scourge/scourge-death.png",
            width = 682,
            height = 594,
            frame_count = 12,
            direction_count = 1,
            axially_symmetrical = false,
            scale = 0.4,
            animation_speed = 0.4
        }
    }
}