---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by heyqule.
--- DateTime: 7/18/2023 8:15 AM
---

return {
    run = {
        main =  {
            filenames = {
                "__erm_zerg_hd_assets__/graphics/entity/units/ultralisk/ultralisk-run-0.png",
                "__erm_zerg_hd_assets__/graphics/entity/units/ultralisk/ultralisk-run-1.png"
            },
            width = 542,
            height = 564,
            frame_count = 10,
            slice = 10,
            lines_per_file = 8,
            line_length = 10,
            axially_symmetrical = false,
            direction_count = 16,
            scale = 0.54,
            animation_speed = 0.2,
        },
        shadow = {
            shift = { 0.2, 0 }
        },
        team =  {
            filenames = {
                "__erm_zerg_hd_assets__/graphics/entity/units/ultralisk/ultralisk-run_teamcolour-0.png",
                "__erm_zerg_hd_assets__/graphics/entity/units/ultralisk/ultralisk-run_teamcolour-1.png"
            },
            width = 542,
            height = 564,
            frame_count = 10,
            slice = 10,
            lines_per_file = 8,
            line_length = 10,
            axially_symmetrical = false,
            direction_count = 16,
            scale = 0.54,
            animation_speed = 0.2,
        },
    },
    attack = {
        main = {
            filenames = {
                "__erm_zerg_hd_assets__/graphics/entity/units/ultralisk/ultralisk-attack-0.png",
                "__erm_zerg_hd_assets__/graphics/entity/units/ultralisk/ultralisk-attack-1.png"
            },
            width = 542,
            height = 564,
            frame_count = 5,
            slice = 5,
            lines_per_file = 8,
            line_length = 5,
            axially_symmetrical = false,
            direction_count = 16,
            scale = 0.54,
            animation_speed = 0.2
        },
        shadow = {
            shift = { 0.2, 0 }
        },
        team = {
            filenames = {
                "__erm_zerg_hd_assets__/graphics/entity/units/ultralisk/ultralisk-attack_teamcolour-0.png",
                "__erm_zerg_hd_assets__/graphics/entity/units/ultralisk/ultralisk-attack_teamcolour-1.png"
            },
            width = 542,
            height = 564,
            frame_count = 5,
            slice = 5,
            lines_per_file = 8,
            line_length = 5,
            axially_symmetrical = false,
            direction_count = 16,
            scale = 0.54,
            animation_speed = 0.2
        },
    },
    corpse = {
        main = {
            filename = "__erm_zerg_hd_assets__/graphics/entity/units/ultralisk/ultralisk-death.png",
            width = 542,
            height = 564,
            frame_count = 11,
            direction_count = 1,
            axially_symmetrical = false,
            scale = 0.54,
            animation_speed = 0.4
        }
    }
}