---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by heyqule.
--- DateTime: 7/18/2023 8:37 PM
---

return {
    run = {
        main =             {
            filename = "__erm_zerg_hd_assets__/graphics/entity/buildings/overmind/overmind_shell.png",
            width = 909,
            height = 664,
            frame_count = 4,
            animation_speed = 0.2,
            direction_count = 1,
            run_mode = "forward-then-backward",
            scale = 0.5
        },
        shadow = {
            shift = {0.2, 0}
        },
        team =             {
            filename = "__erm_zerg_hd_assets__/graphics/entity/buildings/overmind/overmind_shell_teamcolour.png",
            width = 909,
            height = 664,
            frame_count = 4,
            animation_speed = 0.2,
            direction_count = 1,
            run_mode = "forward-then-backward",
            scale = 0.5
        },
    }
}