---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by heyqule.
--- DateTime: 7/18/2023 8:38 PM
---

return {
    run = {
        main = {
            filename = "__erm_zerg_hd_assets__/graphics/entity/buildings/infested_cmd/command_centre.png",
            width = 524,
            height = 646,
            frame_count = 6,
            direction_count = 1,
            animation_speed = 0.2,
            scale = 0.5
        },
        shadow = {
            shift = {0.2, 0}
        },
        light =  {
            filename = "__erm_zerg_hd_assets__/graphics/entity/buildings/infested_cmd/command_centre_mask.png",
            width = 524,
            height = 646,
            frame_count = 6,
            direction_count = 1,
            animation_speed = 0.2,
            scale = 0.5,
            shift = {0.0, -0.05}
        },
        team = {
            filename = "__erm_zerg_hd_assets__/graphics/entity/buildings/infested_cmd/command_centre_teamcolour.png",
            flags = { "mask" },
            width = 524,
            height = 646,
            frame_count = 1,
            repeat_count = 6,
            direction_count = 1,
            animation_speed = 0.2,
            scale = 0.5,
        }
    }
}