---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by heyqule.
--- DateTime: 7/18/2023 8:38 PM
---

return {
    run = {
        main =  {
            filename = "__erm_zerg_hd_assets__/graphics/entity/buildings/infested_cmd/infestor.png",
            width = 524,
            height = 646,
            frame_count = 6,
            direction_count = 1,
            animation_speed = 0.2,
            scale = 0.5
        },
        team = {
            filename = "__erm_zerg_hd_assets__/graphics/entity/buildings/infested_cmd/infestor_teamcolour.png",
            flags = { "mask" },
            width = 524,
            height = 646,
            frame_count = 6,
            direction_count = 1,
            animation_speed = 0.2,
            scale = 0.5,
        }
    }
}
