---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by heyqule.
--- DateTime: 7/18/2023 8:38 PM
---

return {
    run = {
        main =             {
            filename = "__erm_zerg_hd_assets__/graphics/entity/buildings/lair/lair.png",
            width = 786,
            height = 655,
            frame_count = 5,
            animation_speed = 0.2,
            direction_count = 1,
            run_mode = "forward-then-backward",
            scale = 0.5
        },
        shadow = {
            shift = {0.2, 0}
        },
        team =             {
            filename = "__erm_zerg_hd_assets__/graphics/entity/buildings/lair/lair_teamcolour.png",
            width = 786,
            height = 655,
            frame_count = 5,
            animation_speed = 0.2,
            direction_count = 1,
            run_mode = "forward-then-backward",
            scale = 0.5
        },
    }
}