---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by heyqule.
--- DateTime: 7/18/2023 8:38 PM
---

return {
    run = {
        main =  {
            filename = "__erm_zerg_hd_assets__/graphics/entity/buildings/ultralisk_cavern/ultralisk_cavern.png",
            width = 640,
            height = 512,
            frame_count = 3,
            animation_speed = 0.2,
            direction_count = 1,
            run_mode = "forward-then-backward",
            scale = 0.5
        },
        shadow = {
            shift = {0.2, 0}
        },
        team =  {
            filename = "__erm_zerg_hd_assets__/graphics/entity/buildings/ultralisk_cavern/ultralisk_cavern_teamcolour.png",
            width = 640,
            height = 512,
            frame_count = 3,
            animation_speed = 0.2,
            direction_count = 1,
            run_mode = "forward-then-backward",
            scale = 0.5
        },
    }
}